[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
REACT_APP_NETWORK_NAME = "mainnet"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'; script-src 'self'; object-src 'none'; style-src 'self'; default-src 'none'; base-uri 'self'; form-action 'self'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

