[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
REACT_APP_NETWORK_NAME = "mainnet"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

